version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 3d-printing-app
    restart: always
    working_dir: /var/www/
#   uncomment 2 lines under when develop on linux
#    extra_hosts:
#      - host.docker.internal:host-gateway
    volumes:
      - ../src:/var/www
  ngnix:
    image: nginx:1.19-alpine
    container_name: 3d-printing-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phpDatabase
    ports:
      - "3306:3306"