version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: 3d-printing-app
    extra_hosts:
      - host.docker.internal:host-gateway

    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  ngnix:
    image: nginx:1.19-alpine
    container_name: 3d-printing-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phpDatabase
    ports:
      - "3306:3306"
  mailhog:
    container_name: 3d-printing-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025" # mailbox on local machine
      - "1025:1025" # smtp server